name: 'ElectricSQL: Intermediate-Read'

on:
  workflow_dispatch:

jobs:
  electricsql-intermediate-read:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout jepsen-docker
        uses: actions/checkout@v4
        
      - name: Run Intermediate-Read Jepsen Test
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./electricsql-build.sh
          ./electricsql-up.sh
          ./electricsql-run-migrations.sh
          ./electricsql-intermediate-read.sh

      - name: Jepsen, ElectricSQL, and PostgreSQL Logs
        if: ${{ always() }}
        run: |
          docker cp jepsen-control:/jepsen/jepsen-causal-consistency/store $GITHUB_WORKSPACE
          docker logs jepsen-electric-1 > $GITHUB_WORKSPACE/store/current/electricsql.log 
          docker logs jepsen-postgres-1 > $GITHUB_WORKSPACE/store/current/postgresql.log 
          
      - name: 'Jepsen Test Artifacts: results'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'ElectricSQL-intermediate-read-results'
          path: |
            ${{ github.workspace }}/store/current/results.edn
            
      - name: 'Jepsen Test Artifacts: full'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'ElectricSQL-intermediate-read-full'
          path: |
            ${{ github.workspace }}/store/current
            